"""The 50 sample startups `seed_startups` creates. Every name, person and number is invented.

Each row: name, one-line pitch, industry, stage, business model, country, city,
founder, co-founder, co-founder's role, status, days since applying, active
users, paying customers, monthly revenue (USD), then the problem, the solution,
who it's for, and what the founder did before.
"""

# ruff: noqa: E501
# fmt: off
STARTUPS = [
    ("NovaPay", "Modern payments for a global world", "Fintech", "scaling", "Transactional / usage-based", "United States", "New York",
     "Sarah Mitchell", "Marcus Bell", "CTO & co-founder", "accepted", 96, 48000, 2100, 182000,
     "Small exporters lose 3–5% of every invoice to bank transfer fees and wait up to a week for money to arrive from overseas buyers.",
     "NovaPay gives exporters local receiving accounts in 14 currencies and settles to their home bank the same day, for a flat 0.6% fee.",
     "Exporters and online sellers with $200k–$20M in yearly cross-border sales.",
     "ran cross-border payments at a remittance company for seven years"),
    ("WellNex", "Better health, longer lives: preventive care that fits a workday", "Health & biotech", "traction", "Subscription (B2B)", "South Korea", "Seoul",
     "Daniel Kim", "Hana Seo", "Chief medical officer & co-founder", "accepted", 88, 21500, 64, 73000,
     "Office workers skip the annual check-ups that catch chronic disease early, because a visit costs half a working day and results arrive weeks later.",
     "WellNex brings a nurse-led screening to the office, returns results in the app within 48 hours and books follow-ups with a doctor by video.",
     "Employers with 100–5,000 staff who pay for health cover.",
     "worked as a hospital physician before leading product at a telehealth provider"),
    ("EduMint", "Personalised learning for a brighter future", "Education", "traction", "Subscription (B2C)", "India", "Bengaluru",
     "Priya Sharma", "Arjun Nair", "CTO & co-founder", "accepted", 81, 126000, 9400, 58000,
     "Secondary students in large classes fall behind in maths and never get the one-to-one practice that would let them catch up before exams.",
     "EduMint diagnoses each student's gaps in ten minutes and builds a daily 20-minute practice plan, with a tutor on chat when they get stuck.",
     "Students aged 13–17 preparing for board exams, and their parents.",
     "taught secondary maths for five years, then built learning products used by two million students"),
    ("CloudForge", "Build faster, scale smarter: internal platforms without a platform team", "B2B software / SaaS", "fundraising", "Subscription (B2B)", "United Kingdom", "London",
     "Alex Carter", "Nikhil Rao", "CTO & co-founder", "accepted", 74, 3900, 86, 94000,
     "Engineering teams of 20–200 people spend a fifth of their time on deployment pipelines and cloud set-up instead of the product they sell.",
     "CloudForge gives every team a ready-made deployment platform on their own cloud account: environments, pipelines and cost limits in one afternoon.",
     "Software companies with 20–200 engineers and no dedicated platform team.",
     "led infrastructure at two scale-ups and has run platforms serving a billion requests a day"),
    ("GreenLoop", "Cleaner energy for a greener tomorrow: solar that pays for itself", "Climate & energy", "traction", "Subscription (B2B)", "Italy", "Milan",
     "Elena Rossi", "Luca Bianchi", "COO & co-founder", "accepted", 69, 1240, 310, 66000,
     "Small factories want rooftop solar but can't fund the upfront cost, and banks won't lend against a roof they don't understand.",
     "GreenLoop installs and owns the panels, sells the power to the factory for 30% less than the grid, and handles maintenance for 15 years.",
     "Manufacturers with 500–5,000 m² of roof and high daytime power use.",
     "spent eight years financing wind and solar projects at a European energy company"),
    ("GreenGrid", "Battery storage that keeps shops open through power cuts", "Climate & energy", "validation", "Hardware sales", "Jordan", "Amman",
     "Omar Haddad", "Rania Saleh", "CTO & co-founder", "accepted", 63, 420, 95, 31000,
     "Shops and clinics lose stock and working hours to daily power cuts, and diesel generators cost more each year to run and repair.",
     "GreenGrid sells a wall-mounted battery that charges off-peak, switches over in 20 milliseconds and is paid off in monthly instalments.",
     "Small retailers, pharmacies and clinics in cities with unreliable grids.",
     "designed power systems for telecom towers across the Middle East for nine years"),
    ("Kernel", "Catch slow database queries before your customers do", "B2B software / SaaS", "traction", "Subscription (B2B)", "Germany", "Berlin",
     "Lucas Weber", "Mila Novak", "CTO & co-founder", "accepted", 58, 2700, 140, 47000,
     "Engineering teams learn about slow database queries from angry customers, long after the change that caused them has shipped.",
     "Kernel replays production queries against every pull request and blocks the merge when one gets slower, with the fix suggested in the review.",
     "Product engineering teams running Postgres or MySQL in production.",
     "was a database engineer for a decade and maintained a widely used open-source query planner"),
    ("Orbit Labs", "A workspace that turns founders' ideas into shipped progress", "AI & machine learning", "validation", "Subscription (B2B)", "Japan", "Tokyo",
     "Mei Tanaka", "Kenji Mori", "CTO & co-founder", "accepted", 52, 8200, 430, 22000,
     "Founders keep ideas, customer notes and decisions in a dozen tools, and lose the thread between what they learned and what they built.",
     "Orbit Labs captures notes, calls and documents in one place and turns them into a weekly plan, with every task linked to the evidence behind it.",
     "Founding teams of 2–15 people before their Series A.",
     "designed productivity software for six years and started two companies before this one"),
    ("Numa", "An AI research partner for customer insight", "AI & machine learning", "traction", "Subscription (B2B)", "Canada", "Toronto",
     "Hannah Lindqvist", "Dev Patel", "CTO & co-founder", "accepted", 47, 5100, 210, 61000,
     "Product teams record hundreds of customer interviews a year and use almost none of them, because nobody has time to go back through the recordings.",
     "Numa transcribes every interview, groups what customers said by theme and answers questions with the exact quotes and clips as evidence.",
     "Product and research teams at software companies with 50–2,000 staff.",
     "ran user research at a design software company and interviewed more than 900 customers"),
    ("Relay", "Payments infrastructure for founders selling worldwide", "Fintech", "fundraising", "Transactional / usage-based", "Singapore", "Singapore",
     "Wei Jie Tan", "Aisha Rahman", "COO & co-founder", "accepted", 44, 1900, 620, 138000,
     "Online businesses in Southeast Asia stitch together five payment providers to accept local wallets, cards and bank transfers across the region.",
     "Relay offers one integration for 40 local payment methods in nine countries, with settlement in a single currency and one reconciliation report.",
     "Online merchants and marketplaces selling across Southeast Asia.",
     "built payment integrations for a regional marketplace for six years"),
    ("Harvestly", "Fair prices for smallholder farmers, straight from the buyer", "Marketplaces", "traction", "Marketplace / take rate", "Kenya", "Nairobi",
     "Wanjiru Kamau", "Peter Otieno", "Head of operations & co-founder", "accepted", 41, 14300, 380, 39000,
     "Smallholder farmers sell to middlemen at half the city price because they can't reach buyers or move produce before it spoils.",
     "Harvestly takes orders from restaurants and grocers a day ahead, collects from farms at dawn and pays farmers by mobile money the same evening.",
     "Farmers within 150 km of a city, and the restaurants and grocers they supply.",
     "grew up on a family farm and ran logistics for a food distributor for five years"),
    ("Medibridge", "Specialist second opinions in 48 hours, wherever you live", "Health & biotech", "validation", "Transactional / usage-based", "Nigeria", "Lagos",
     "Chidi Okonkwo", "Amara Eze", "Chief medical officer & co-founder", "accepted", 38, 6200, 1150, 27000,
     "Patients outside major cities wait months and travel for days to see a specialist, often for a question that needs twenty minutes.",
     "Medibridge lets a local doctor send scans and notes to a vetted specialist and get a written opinion in 48 hours, for a fixed fee.",
     "General practitioners and clinics serving towns without specialist care.",
     "practised as a radiologist before building clinical software for hospital groups"),
    ("Lumen Tutor", "Reading practice that listens, for children who are behind", "Education", "validation", "Subscription (B2C)", "United States", "Austin",
     "Grace Thompson", "Miguel Santos", "CTO & co-founder", "accepted", 35, 18900, 2300, 19000,
     "One in three children leaves primary school unable to read fluently, and teachers have no time to listen to each child read aloud.",
     "Lumen Tutor listens as a child reads from a tablet, helps with the words they stumble on and shows the teacher who needs attention.",
     "Primary schools and parents of children aged 5–9.",
     "taught reading for eight years and trained teachers in three school districts"),
    ("Stackwise", "Know what every software subscription costs, and who uses it", "B2B software / SaaS", "traction", "Subscription (B2B)", "Netherlands", "Amsterdam",
     "Sanne de Vries", "Tomás Herrera", "CTO & co-founder", "accepted", 33, 960, 118, 52000,
     "Companies with 100 staff pay for around 120 software tools, a third of them unused, and nobody owns the list or the renewals.",
     "Stackwise reads the accounts and single sign-on logs, shows every subscription with its real usage, and cancels or downgrades in one click.",
     "Finance and IT leads at companies with 50–1,000 employees.",
     "was a finance director at two software companies and ran procurement by spreadsheet"),
    ("Aerofarm Labs", "Greenhouse yields from a shipping container", "Deep tech & hardware", "mvp", "Hardware sales", "United Arab Emirates", "Dubai",
     "Layla Al-Mansouri", "Yusuf Demir", "Chief engineer & co-founder", "accepted", 30, 12, 4, 15000,
     "Desert cities import 85% of their fresh vegetables, which arrive a week old at three times the price they cost to grow.",
     "Aerofarm Labs builds container farms that grow leafy greens with 95% less water, run by software that tunes light and nutrients to each crop.",
     "Supermarkets, hotels and caterers in hot, dry climates.",
     "researched plant science for six years and managed a commercial vertical farm"),
    ("Tallybook", "Bookkeeping by phone camera for market traders", "Fintech", "traction", "Subscription (B2C)", "Ghana", "Accra",
     "Kwame Mensah", "Efua Boateng", "Head of product & co-founder", "accepted", 28, 67000, 5800, 24000,
     "Market traders keep sales in notebooks or their heads, so they can't prove income to get a loan and don't know which goods make money.",
     "Tallybook records a sale from a photo or a voice note, shows daily profit and builds the income record that lenders ask for.",
     "Informal traders and small shop owners with a smartphone.",
     "spent six years lending to small traders at a microfinance bank"),
    ("Routewell", "Delivery routes that drivers actually follow", "Mobility & logistics", "traction", "Subscription (B2B)", "Brazil", "São Paulo",
     "Rafael Almeida", "Beatriz Costa", "CTO & co-founder", "accepted", 26, 3400, 92, 44000,
     "Courier companies plan routes on software that ignores how drivers really work, so drivers reorder stops and a fifth of deliveries arrive late.",
     "Routewell learns from each driver's past rounds, plans routes they accept, and re-plans on the road when a stop fails or traffic builds.",
     "Regional courier and grocery delivery fleets with 20–500 vehicles.",
     "managed a 300-van delivery depot before studying operations research"),
    ("Clarity Legal", "Contracts small businesses can read and sign in minutes", "B2B software / SaaS", "validation", "Subscription (B2B)", "Australia", "Melbourne",
     "Olivia Bennett", "James Nguyen", "CTO & co-founder", "accepted", 24, 2100, 260, 18000,
     "Small businesses sign supplier and client contracts without reading them, because a lawyer's review costs more than the deal is worth.",
     "Clarity Legal explains any contract in plain words, flags the unusual clauses and suggests the edits a lawyer would ask for.",
     "Agencies, consultancies and trades with 2–50 staff.",
     "practised commercial law for seven years, mostly for small companies"),
    ("Pulsebeat", "Heart monitoring at home after surgery", "Health & biotech", "mvp", "Hardware sales", "Sweden", "Stockholm",
     "Erik Johansson", "Sofia Lindberg", "Chief medical officer & co-founder", "accepted", 22, 340, 6, 9000,
     "One in six heart-surgery patients is readmitted within a month, usually for a rhythm problem nobody saw developing at home.",
     "Pulsebeat is a patch worn for 30 days that streams heart rhythm to the ward, alerting nurses to trouble days before it becomes an emergency.",
     "Cardiac units in public and private hospitals.",
     "built medical devices for nine years and holds three patents in wearable sensing"),
    ("Shelfsense", "Never out of stock: shelf cameras for small grocers", "E-commerce & retail", "validation", "Subscription (B2B)", "Spain", "Barcelona",
     "Carmen Ortega", "Pau Vidal", "CTO & co-founder", "accepted", 20, 180, 44, 13000,
     "Independent grocers lose 8% of sales to empty shelves they only notice when a customer asks for something that has run out.",
     "Shelfsense clips small cameras to existing shelves, spots gaps every ten minutes and sends staff a restocking list ordered by lost sales.",
     "Independent grocers and small chains with 1–40 shops.",
     "ran three family supermarkets and studied computer vision at night"),
    ("Finlit", "Money lessons teenagers finish", "Education", "validation", "Subscription (B2B)", "South Africa", "Cape Town",
     "Thabo Molefe", "Zanele Dlamini", "Head of learning & co-founder", "accepted", 18, 31000, 58, 11000,
     "Teenagers leave school without knowing how interest, tax or a payslip work, and the lessons that exist are worksheets they ignore.",
     "Finlit teaches money through a game where students run a household for a simulated year, with lessons mapped to the national curriculum.",
     "Secondary schools and youth programmes.",
     "worked in retail banking and volunteered teaching budgeting in township schools"),
    ("Quarry AI", "Answers from your company's documents, with the source", "AI & machine learning", "fundraising", "Subscription (B2B)", "France", "Paris",
     "Camille Laurent", "Antoine Dubois", "CTO & co-founder", "accepted", 16, 7400, 73, 88000,
     "Engineers at industrial companies spend hours hunting through manuals, drawings and old emails for answers that someone already wrote down.",
     "Quarry AI indexes technical documents where they sit and answers questions with the page and paragraph it found them on, in any language.",
     "Engineering and maintenance teams at manufacturers and utilities.",
     "was a research engineer in language models and maintained plant documentation as a student"),
    ("Tendril", "Soil sensors that tell farmers when to water", "Deep tech & hardware", "validation", "Hardware sales", "Israel", "Tel Aviv",
     "Noa Friedman", "Eitan Katz", "Chief engineer & co-founder", "in_review", 15, 260, 38, 16000,
     "Fruit growers over-water by a third because they irrigate on a calendar, wasting water and washing away fertiliser they paid for.",
     "Tendril's probes measure moisture at root depth and text the grower a daily irrigation plan for each block, with no network set-up.",
     "Orchards and vineyards of 10–500 hectares.",
     "grew up in an orchard family and designed low-power sensors for seven years"),
    ("Paywise", "Wages on demand, without the payday loan", "Fintech", "traction", "Subscription (B2B)", "Mexico", "Mexico City",
     "Valeria Ramírez", "Diego Fuentes", "CTO & co-founder", "in_review", 14, 42000, 61, 35000,
     "Hourly workers borrow at 300% interest to cover the gap before payday, even though they have already earned the money.",
     "Paywise lets employees withdraw wages they have already earned for a small flat fee, paid for by the employer as a benefit.",
     "Employers of hourly staff in retail, hospitality and manufacturing.",
     "ran payroll operations for a 12,000-person retailer"),
    ("Dockhand", "Book a warehouse loading slot in two taps", "Mobility & logistics", "validation", "Subscription (B2B)", "Poland", "Warsaw",
     "Marta Kowalska", "Piotr Zielinski", "CTO & co-founder", "in_review", 13, 5600, 27, 14000,
     "Lorry drivers wait an average of three hours at warehouses because loading slots are arranged by phone and nobody knows who arrives when.",
     "Dockhand gives warehouses a live booking calendar; drivers reserve a slot from their phone and gates open on arrival.",
     "Warehouses and distribution centres with 5–60 loading bays.",
     "dispatched lorries for a freight forwarder for six years"),
    ("Bloomwell", "Therapy that starts this week, not in four months", "Health & biotech", "traction", "Subscription (B2C)", "Ireland", "Dublin",
     "Aoife Byrne", "Conor Walsh", "Clinical director & co-founder", "in_review", 12, 9800, 1450, 41000,
     "People who ask for mental-health support wait months for a first appointment, and many give up before it comes.",
     "Bloomwell matches each person with a licensed therapist within three days and runs sessions by video, with exercises between them.",
     "Adults seeking therapy, and the employers and insurers who pay for it.",
     "is a clinical psychologist who ran a community mental-health service"),
    ("Sprout Kitchens", "Shared commercial kitchens for delivery-only restaurants", "Consumer", "traction", "Subscription (B2B)", "Indonesia", "Jakarta",
     "Putri Wijaya", "Adi Santoso", "COO & co-founder", "in_review", 11, 74, 74, 29000,
     "A cook with a good menu needs $40,000 and six months to open a restaurant, and most of that money goes on a dining room nobody needs.",
     "Sprout Kitchens rents licensed kitchen stations by the month, with delivery apps, packaging and couriers already set up.",
     "Independent chefs and small restaurant brands selling by delivery.",
     "opened four restaurants and closed two, which taught her where the money goes"),
    ("Vectorly", "Design files to production code, kept in sync", "B2B software / SaaS", "validation", "Subscription (B2B)", "Portugal", "Lisbon",
     "Inês Carvalho", "Rui Marques", "CTO & co-founder", "in_review", 10, 3300, 190, 12000,
     "Front-end developers rebuild by hand every screen a designer draws, and the two drift apart within a week of launch.",
     "Vectorly turns design files into components in the team's own code style and opens a pull request whenever the design changes.",
     "Product teams with separate designers and front-end developers.",
     "worked as both a product designer and a front-end developer for eight years"),
    ("Solara Home", "Rooftop solar on a monthly plan, installed in a day", "Climate & energy", "traction", "Subscription (B2C)", "Pakistan", "Lahore",
     "Ayesha Malik", "Bilal Hussain", "Head of engineering & co-founder", "in_review", 9, 2800, 2800, 57000,
     "Households pay more each year for unreliable grid power, but a solar system costs a year's income to buy outright.",
     "Solara Home installs panels and a battery for no money down and charges a monthly fee lower than the old electricity bill.",
     "Home owners in cities with frequent power cuts and high tariffs.",
     "was an electrical engineer at a utility before selling solar door to door"),
    ("Kiln", "Low-carbon cement made from industrial waste", "Deep tech & hardware", "mvp", "Licensing", "Denmark", "Copenhagen",
     "Freja Nielsen", "Jonas Holm", "Chief scientist & co-founder", "in_review", 8, 3, 2, None,
     "Cement makes 8% of the world's carbon emissions, and producers have no drop-in alternative that meets building standards.",
     "Kiln replaces 60% of the clinker in cement with treated steel slag, cutting emissions in half with the strength that standards require.",
     "Cement producers and large construction firms with carbon targets.",
     "holds a doctorate in materials chemistry and worked in a cement research lab"),
    ("Mentorly", "A working professional for every first-generation student", "Education", "validation", "Subscription (B2B)", "United States", "Chicago",
     "Jasmine Carter", "Andre Williams", "Head of partnerships & co-founder", "in_review", 7, 11200, 31, 17000,
     "First-generation university students drop out at twice the rate of their peers, often because nobody they know has done it before.",
     "Mentorly pairs each student with a graduate working in the field they want, and gives both a term-by-term plan to follow.",
     "Universities and scholarship programmes.",
     "was the first in her family to graduate and ran student success programmes for six years"),
    ("Cartwheel", "Checkout that remembers shoppers across independent shops", "E-commerce & retail", "traction", "Transactional / usage-based", "Turkey", "Istanbul",
     "Elif Yıldız", "Can Aydın", "CTO & co-founder", "in_review", 6, 240000, 870, 63000,
     "Independent online shops lose seven in ten baskets at checkout, because shoppers won't type their card and address again.",
     "Cartwheel is a shared one-tap checkout: a shopper who has bought from any shop in the network pays at all of them with a fingerprint.",
     "Independent online shops with $100k–$10M in yearly sales.",
     "led checkout at a large marketplace and raised its conversion by a fifth"),
    ("Signalcraft", "Find the machine that will fail next week", "AI & machine learning", "validation", "Subscription (B2B)", "Czech Republic", "Prague",
     "Tereza Novotná", "Jakub Svoboda", "CTO & co-founder", "changes_requested", 19, 46, 9, 21000,
     "Factories repair machines after they break, and an hour of unplanned downtime on a production line costs more than a month of maintenance.",
     "Signalcraft listens to the vibration of each motor with a clip-on sensor and warns the maintenance team a week before a bearing fails.",
     "Mid-sized manufacturers with 50–500 rotating machines.",
     "worked as a maintenance engineer in car plants before studying signal processing"),
    ("Homestead", "Rent reporting that builds a credit score", "Fintech", "validation", "Subscription (B2C)", "Canada", "Vancouver",
     "Ethan Clarke", "Meera Shah", "CTO & co-founder", "changes_requested", 17, 15600, 4100, 16000,
     "Renters pay on time for years and still have no credit history, so they pay higher rates when they finally apply for a loan.",
     "Homestead verifies rent payments from the renter's bank and reports them to the credit bureaus each month.",
     "Renters aged 22–40 with a thin credit file.",
     "worked in credit risk at a bank and rented for eleven years"),
    ("Papertrail", "Customs paperwork filled in from the invoice", "Mobility & logistics", "mvp", "Transactional / usage-based", "Vietnam", "Ho Chi Minh City",
     "Linh Nguyen", "Minh Tran", "CTO & co-founder", "changes_requested", 21, 85, 14, 6000,
     "Small exporters fill in the same shipment details on nine customs forms, and one mistake holds a container at the port for a week.",
     "Papertrail reads the commercial invoice and packing list, completes every customs form and checks them against the destination's rules.",
     "Exporters and freight forwarders shipping 5–500 containers a year.",
     "was a customs broker for seven years"),
    ("Brightside", "Daily check-ins for people living alone", "Consumer", "validation", "Subscription (B2C)", "Japan", "Osaka",
     "Yuki Sato", "Haruto Ito", "CTO & co-founder", "submitted", 5, 4300, 1900, 14000,
     "Families worry about elderly parents who live alone, and find out about a fall or an illness only when a phone call goes unanswered.",
     "Brightside makes a friendly daily call, notices changes in mood or routine and tells the family the same day when something seems wrong.",
     "Adults with a parent over 70 living alone.",
     "worked as a care manager for older people for eight years"),
    ("Ledgerline", "The accounts payable inbox that pays the right invoice once", "Fintech", "validation", "Subscription (B2B)", "Germany", "Munich",
     "Jonas Becker", "Lena Hoffmann", "CTO & co-founder", "submitted", 5, 720, 48, 19000,
     "Finance teams retype supplier invoices from email into the accounts system, and pay one in fifty twice or to the wrong account.",
     "Ledgerline reads each invoice as it arrives, matches it to the order and the delivery, and queues it for approval with duplicates flagged.",
     "Finance teams at companies with 50–1,000 staff.",
     "was a financial controller who processed 4,000 invoices a month"),
    ("Tidepool", "Fish farm monitoring from a floating sensor", "Deep tech & hardware", "mvp", "Hardware sales", "Norway", "Bergen",
     "Ingrid Solberg", "Henrik Dahl", "Chief engineer & co-founder", "submitted", 4, 9, 3, 4000,
     "Fish farmers lose a tenth of their stock each year to oxygen drops and disease that are spotted only when fish start to die.",
     "Tidepool's buoy measures oxygen, temperature and feeding behaviour around the clock and warns the farmer hours before stock is at risk.",
     "Salmon and trout farms with 4–40 pens.",
     "is a marine biologist who worked on fish health at an aquaculture company"),
    ("Parcelpoint", "Collect your parcel from the corner shop", "E-commerce & retail", "traction", "Transactional / usage-based", "Egypt", "Cairo",
     "Nour El-Sayed", "Karim Mostafa", "COO & co-founder", "submitted", 4, 58000, 1300, 26000,
     "A third of home deliveries fail on the first attempt because nobody is in, and every repeat trip costs the courier more than the delivery fee.",
     "Parcelpoint turns neighbourhood shops into pick-up points: couriers drop many parcels in one stop and shoppers collect on their way home.",
     "Courier companies and online shops delivering in dense cities.",
     "ran last-mile operations for an online retailer"),
    ("Scholarbridge", "Scholarship applications, matched and half filled in", "Education", "mvp", "Subscription (B2C)", "Philippines", "Manila",
     "Maria Santos", "Paolo Reyes", "CTO & co-founder", "submitted", 3, 7600, 420, 3000,
     "Millions in scholarships go unclaimed each year because students don't know which they qualify for and each form takes days.",
     "Scholarbridge asks a student twenty questions, lists the scholarships they qualify for and fills in the shared parts of each application.",
     "Final-year school students and undergraduates.",
     "won four scholarships herself and advised students at a university admissions office"),
    ("Fernway", "Carbon accounts for small manufacturers, from their invoices", "Climate & energy", "validation", "Subscription (B2B)", "United Kingdom", "Manchester",
     "Oliver Hughes", "Fatima Ahmed", "Head of data & co-founder", "submitted", 3, 310, 52, 15000,
     "Big buyers now demand carbon figures from every supplier, and a small manufacturer has no staff or budget for a consultant to work them out.",
     "Fernway calculates a company's emissions from its energy bills and purchase invoices and produces the report its customers ask for.",
     "Manufacturers with 20–500 staff who supply large corporations.",
     "audited carbon reports for a consultancy for five years"),
    ("Hearth", "Group buying for home insulation, street by street", "Marketplaces", "validation", "Marketplace / take rate", "Belgium", "Ghent",
     "Lotte Peeters", "Bram Janssens", "COO & co-founder", "submitted", 3, 2900, 640, 18000,
     "Home owners put off insulating because quotes are confusing and expensive, while installers waste days driving between single jobs.",
     "Hearth signs up a whole street at once, negotiates one price and schedules the installer to do every house in the same week.",
     "Owners of houses built before 1990.",
     "organised neighbourhood energy schemes for a city council"),
    ("Okapi Health", "A pharmacy stock room that orders for itself", "Health & biotech", "traction", "Subscription (B2B)", "Uganda", "Kampala",
     "Grace Nakato", "Samuel Okello", "CTO & co-founder", "submitted", 2, 1100, 290, 23000,
     "Community pharmacies run out of essential medicines every week because they order by guesswork and wholesalers deliver late.",
     "Okapi Health tracks each sale, forecasts what will run out and places the order with the cheapest wholesaler that can deliver in time.",
     "Independent pharmacies and small clinic dispensaries.",
     "is a pharmacist who managed supply for 40 rural health centres"),
    ("Loomstack", "Made-to-order clothing from idle factory hours", "Marketplaces", "validation", "Marketplace / take rate", "Bangladesh", "Dhaka",
     "Farhana Islam", "Tanvir Hossain", "Head of supply & co-founder", "submitted", 2, 430, 120, 31000,
     "Small clothing brands can't meet factory minimums of 1,000 pieces, while factories sit idle a fifth of the time between large orders.",
     "Loomstack lets brands order runs of 50 pieces, which it slots into unused hours at audited factories and ships in three weeks.",
     "Independent clothing brands selling online.",
     "managed production planning at a garment exporter for nine years"),
    ("Ping Mobility", "Shared electric mopeds for delivery riders", "Mobility & logistics", "traction", "Subscription (B2C)", "Colombia", "Bogotá",
     "Santiago Gómez", "Daniela Ruiz", "COO & co-founder", "submitted", 2, 3700, 3700, 48000,
     "Delivery riders spend a third of what they earn on fuel and repairs for motorbikes they are still paying off.",
     "Ping Mobility rents electric mopeds by the week with battery swaps and repairs included, for less than riders spend on fuel alone.",
     "Full-time riders for food and parcel delivery apps.",
     "was a delivery rider through university and later ran a fleet of 200 bikes"),
    ("Cobalt Security", "Phishing drills your staff don't resent", "B2B software / SaaS", "validation", "Subscription (B2B)", "Estonia", "Tallinn",
     "Kristjan Tamm", "Liis Saar", "CTO & co-founder", "submitted", 2, 8900, 77, 20000,
     "Nine in ten security breaches start with a staff member clicking a link, and yearly training videos change nobody's behaviour.",
     "Cobalt Security sends each person realistic practice attacks based on their role and teaches them in the moment, in under a minute.",
     "IT and security leads at companies with 50–2,000 staff.",
     "led incident response at a bank and investigated more than 200 breaches"),
    ("Mealmap", "A week of dinners planned around what's on offer", "Consumer", "mvp", "Advertising", "United States", "Denver",
     "Emily Parker", "Noah Kim", "CTO & co-founder", "submitted", 1, 22400, None, 2000,
     "Families throw away a quarter of the food they buy and spend an hour a week deciding what to cook.",
     "Mealmap plans a week of dinners from the supermarket's current offers and what is already in the cupboard, and sends the list to the shop.",
     "Households with children who cook most nights.",
     "was a dietitian and wrote meal plans for 600 families"),
    ("Aqualine", "Leak detection for city water pipes", "Deep tech & hardware", "validation", "Subscription (B2B)", "Chile", "Santiago",
     "Catalina Vargas", "Matías Silva", "Chief engineer & co-founder", "submitted", 1, 14, 5, 12000,
     "Cities lose a third of their treated water to leaks underground, and find them only when a street floods.",
     "Aqualine fits acoustic sensors to existing hydrants and pinpoints a leak to within two metres, while it is still the size of a pinhole.",
     "Municipal water utilities serving 50,000–2 million people.",
     "was a hydraulic engineer at a water utility for eight years"),
    ("Storyloom", "Children's books in languages publishers ignore", "Consumer", "validation", "Subscription (B2C)", "Ethiopia", "Addis Ababa",
     "Selam Tesfaye", "Dawit Bekele", "Head of content & co-founder", "submitted", 1, 16800, 2200, 7000,
     "Hundreds of millions of children have no picture books in the language they speak at home, because print runs that small never pay.",
     "Storyloom commissions local authors and illustrators, publishes on any phone and prints on demand for schools, in 30 languages so far.",
     "Parents and primary schools in multilingual countries.",
     "edited children's books for a publisher and translated in four languages"),
    ("Benchmark Bio", "Lab results in an hour, without sending samples away", "Health & biotech", "mvp", "Hardware sales", "Switzerland", "Basel",
     "Lena Keller", "Marco Frei", "Chief scientist & co-founder", "submitted", 1, 21, 3, None,
     "Rural clinics send blood samples to a city lab and wait three days, so patients are treated on a guess or not at all.",
     "Benchmark Bio's desktop analyser runs the twelve most common blood tests from a finger prick in under an hour, operated by a nurse.",
     "Rural clinics and general practices far from a laboratory.",
     "spent a decade developing diagnostic instruments at a life-science company"),
]
# fmt: on
