# Generated by Django 5.2.17 on 2026-10-03 07:58

import apps.content.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=120)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("Applying to the program", "Applying to the program"),
                            ("Investing or partnerships", "Investing or partnerships"),
                            ("Mentoring", "Mentoring"),
                            ("Press", "Press"),
                            ("Something else", "Something else"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("issue", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("excerpt", models.TextField(max_length=400)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Fundraising", "Fundraising"),
                            ("Building", "Building"),
                            ("AI", "AI"),
                            ("Founder Stories", "Founder Stories"),
                            ("Program News", "Program News"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Fundup Club Program Team", max_length=120
                    ),
                ),
                (
                    "published_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Leave at 0 to estimate from the text.",
                        verbose_name="read time (minutes)",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Paragraphs separated by a blank line. A line starting with '## ' is a heading; lines starting with '- ' make a list; lines starting with '> ' make a quote, and a last line '> — Name' credits it."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_on", "-issue"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Demo Day", "Demo Day"),
                            ("Workshop", "Workshop"),
                            ("Office Hours", "Office Hours"),
                            ("Networking", "Networking"),
                            ("Info Session", "Info Session"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("In person", "In person"), ("Online", "Online")],
                        default="In person",
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text='City for in-person events; "Online" otherwise.',
                        max_length=80,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "tz",
                    models.CharField(
                        default="America/Los_Angeles",
                        help_text="Times are shown in this zone, e.g. America/Los_Angeles, Europe/London.",
                        max_length=64,
                        validators=[apps.content.models.validate_timezone],
                        verbose_name="time zone",
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=100)),
                ("summary", models.TextField(max_length=400)),
                (
                    "about",
                    models.TextField(
                        help_text="Paragraphs, separated by a blank line."
                    ),
                ),
                (
                    "takeaways",
                    models.TextField(
                        blank=True,
                        help_text="One per line.",
                        verbose_name="what you'll get",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="who it's for"
                    ),
                ),
                (
                    "venue",
                    models.TextField(
                        blank=True,
                        help_text="Address for in-person events. Only sent to registered guests.",
                    ),
                ),
                (
                    "online_url",
                    models.URLField(
                        blank=True,
                        help_text="Online events. Only sent to registered guests.",
                        max_length=500,
                        verbose_name="joining link",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "end"],
                        name="content_eve_is_publ_b75f74_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gt", models.F("start"))),
                        name="event_ends_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.CharField(help_text="As shown, e.g. 4:00 PM", max_length=20),
                ),
                ("item", models.CharField(max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda",
                        to="content.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("source", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="subscriber_email_ci_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="content.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "email"), name="one_registration_per_email"
                    )
                ],
            },
        ),
    ]
