# Generated by Django 5.2.17 on 2026-10-03 18:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(
                default=100, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                help_text="Paragraphs separated by a blank line. A line starting with '## ' (or '### ') is a heading; lines starting with '- ' (or '1. ') make a list; lines starting with '> ' make a quote, and a last line '> — Name' credits it."
            ),
        ),
    ]
