# Generated by Django 5.2.17 on 2026-10-03 07:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="application",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("declined", "Not selected"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("profile", models.JSONField(default=dict)),
                ("startup", models.JSONField(default=dict)),
                ("team", models.JSONField(default=dict)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "startup_name",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=16)),
                ("industry", models.CharField(blank=True, default="", max_length=40)),
                (
                    "founder_name",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("tagline", models.CharField(blank=True, default="", max_length=120)),
                ("team_score", models.FloatField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "by",
                    models.CharField(
                        choices=[("founder", "Founder"), ("support", "Review team")],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                            ("status", "Status change"),
                            ("note", "Note"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="InternalNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="applications.application",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="Scorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("solution", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("market", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("team", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("traction", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accept"),
                            ("interview", "Interview"),
                            ("decline", "Decline"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="applications.application",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "submitted_at"], name="applications_queue"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "updated_at"], name="applications_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["assignee", "status"], name="applications_assignee"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "draft",
                            "submitted",
                            "in_review",
                            "changes_requested",
                            "accepted",
                            "declined",
                        ],
                    )
                ),
                name="applications_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(
                fields=["application", "at"], name="application_events_by_app"
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecard",
            constraint=models.UniqueConstraint(
                fields=("application", "reviewer"), name="one_scorecard_per_reviewer"
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("problem__isnull", True),
                    models.Q(("problem__gte", 1), ("problem__lte", 5)),
                    _connector="OR",
                ),
                name="scorecard_problem_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("solution__isnull", True),
                    models.Q(("solution__gte", 1), ("solution__lte", 5)),
                    _connector="OR",
                ),
                name="scorecard_solution_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("market__isnull", True),
                    models.Q(("market__gte", 1), ("market__lte", 5)),
                    _connector="OR",
                ),
                name="scorecard_market_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("team__isnull", True),
                    models.Q(("team__gte", 1), ("team__lte", 5)),
                    _connector="OR",
                ),
                name="scorecard_team_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("traction__isnull", True),
                    models.Q(("traction__gte", 1), ("traction__lte", 5)),
                    _connector="OR",
                ),
                name="scorecard_traction_1_to_5",
            ),
        ),
    ]
