# Generated by Django 5.2.17 on 2026-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="logo",
            field=models.FileField(
                blank=True, default="", max_length=120, upload_to="startups"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="photo",
            field=models.FileField(
                blank=True, default="", max_length=120, upload_to="founders"
            ),
        ),
    ]
